PluginException: 	Added serialVersionUID 	Marked printStack, thrower as transient PluginManager: 	removed unnecessary super call build.xml: 	Updated build file so that it builds the project before packaging it into a .jar file